repos:
  # NOTE: Generic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
  # NOTE: Formatters and linters
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.57.0
    hooks:
      - id: oxlint
  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.42.0
    hooks:
      - id: oxfmt
