import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "مقرأة النيل",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`antialiased min-h-screen w-screen bg-[#EBF0EB]`}>{children}</body>
    </html>
  );
}
